### PR TITLE
LONDON CLASS 8 - DAVOOD KHOSHNOOD - HTML/CSS - WEEK2

### PR DESCRIPTION
**Pull request by DavoodKhoshnood**
It's Karma clone project.

**Volunteers: Are you marking this coursework?** _You can find a guide on how to mark this coursework in `HOW_TO_MARK.md` in the root of this repository_

# Your Details

- Your Name: Davood Khoshnood
- Your City: London
- Your Slack Name: Davood

# Homework Details

- Module: HTML/CSS
- Week: 2

# Notes

- What did you find easy? All

- What did you find hard? Fully easy.

- What do you still not understand? Nothing.

- Any other notes?

### CODE REVIEW

**Comment by DiegoJunior0** [comment]
Hi Davood, this is excellent work so far, well done! Your html is very clean!
Only thing I would say is, try to pay closer attention to detail to the reference image: font sizes, font weights and spacing/padding. If it helps you can open the refence image in your browser.
Also see if you can get the menu button for the mobile version to align to the right.

**Comment by DavoodKhoshnood** [comment]
Hi Henry, I'll check it asap and I'll commit it. thank you so much.

**Comment by DiegoJunior0** [comment]
Great updates Davood, mobile version looking much better

**Comment by DavoodKhoshnood** [comment]
Thank you Henry, I hope it was acceptable.

**Comment by DiegoJunior0** [comment]
@DavoodKhoshnood have you been able to work on the store page?

**Comment by DavoodKhoshnood** [comment]
> @DavoodKhoshnood have you been able to work on the store page?

Hi Henry, unfortunately I had not. It's a shame I was busy. I hope I'll do that today.
Thanks.

**Review by DiegoJunior0 — APPROVED** [review]

**Pull request closed without merging**
